version: '3'
services:
  php-apache:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html:z
    network_mode: host
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    volumes:
      - ./mysql:/var/local:z
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv="/var/local"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_DATABASE: 'trabbd'
    network_mode: host